version: '3.8'
services:
  backend:
    build:
        context: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=/app/wsgi.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
